#!/bin/bash
#compile and run main

g++ -std=c++11 -pedantic -Wno-long-long -falign-loops=32 -I../include main.C -o main -Wl,--start-group -L../v8libs -lv8_base -lv8_libbase -lv8_nosnapshot -lv8_libplatform -licuuc -licui18n -licudata -Wl,--end-group -lrt -ldl -pthread

./main
